server:
  context-path: /
  port: 8085
      
spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/book_library?useUnicode=true&serverTimezone=UTC"
    username: "root"
    password: "root"
  jooq:
    sql-dialect: mysql